include $(MOD_CFG)

# Custmization Begin
# 
# DIR_SRC := src
# DIR_INC := inc
#
# TYPE_INC := .h
# TYPE_SRC := .c
# TYPE_OBJ := .o
# TYPE_DEP := .dep
#
# Custmization End

include $(CMD_CFG)

include $(MOD_RULE)
