# $(call variable,param,param)
# $(0) is the variable, while $(1), $(2), etc. are the params.

# 在哪种情况下使用呢

sweet_new_fn = variable_name: $(0) first_param: $(1) second_param: $(2) empty_param: $(3)

all:
	@echo $(call sweet_new_fn, go, trigger)