
JAVA_HOME := java home
export var := D.T.Software
new := TDelphi

test :
	@echo "JAVA_HOME => $(JAVA_HOME)"
	@echo "make another file ..."
	@$(MAKE) -f makefile.2
	@$(MAKE) -f makefile.2 new:=$(new)
	