# ex1
# x := foo
# y := $(x)b
# x := new

# ex2
# x = foo
# y = $(x)b
# x = new

# a = $(b)
# b = $(c)
# c = hello-makefile

# ex3
# x := foo
# y := $(x)b
# x ?= new

# ex4
# x := foo
# y := $(x)b
# x += new

.PHONY : test

test :
	@echo "x => $(x)"
	@echo "y => $(y)"
	@echo "a => $(a)"
	@echo "b => $(b)"
	@echo "c => $(c)"
