all:
	@echo "hello"		# sliencing，在命令前加一个@，不打印命令本身
	echo "world"		# echoing，不加@时，打印命令本身

# Add an @ before a command to stop it from being printed
# You can also run make with -s to add an @ before each line